<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4A3N2QO" failures="1" tests="4" name="Test" time="39.333" errors="0" timestamp="2023-05-27T07:39:04 SAST">
  <testcase classname="tests.FourTest" name="fourTest" time="11.792">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.FourTest.fourTest(FourTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- fourTest -->
  <testcase classname="tests.TwoTest" name="twoTest" time="7.792"/>
  <testcase classname="tests.LoginTest" name="login" time="5.455"/>
  <testcase classname="tests.ThreeTest" name="threeTest" time="7.563"/>
</testsuite> <!-- Test -->
